### ISSUE TITLE
Node.js addon result Error!

### ISSUE THREAD

**Issue by but0n** [but0n/recastCLI.js#4]
## Correct
![image](https://user-images.githubusercontent.com/7625588/37093691-35b34a02-224b-11e8-9b6e-d488c0617875.png)

## Bad result
![image](https://user-images.githubusercontent.com/7625588/37093696-3dc2aaee-224b-11e8-99eb-4bee0a74e688.png)

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/37129267-235dc2d8-22b9-11e8-8605-085064e414fd.png)

**Comment by but0n** [comment]
使用 `rcMeshLoaderObj::load` 直接读取文件能正常工作:

![image](https://user-images.githubusercontent.com/7625588/37129443-f43467cc-22b9-11e8-9786-2d42e56707fa.png)

6217757
问题应该出在 `rcMeshLoaderObj::readBuffer` 上

**Comment by but0n** [comment]
但是readBuffer之前测试是正常的, See #1

**Comment by but0n** [comment]
https://stackoverflow.com/a/16639079/6940633
v8 string problem

**Comment by but0n** [comment]
### f044732
v8 sucks 😠 
![image](https://user-images.githubusercontent.com/7625588/37142515-47e0c9e0-22f3-11e8-8166-65250ef51ed3.png)

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/37149578-883a92f8-2309-11e8-8b83-c367a494dcd1.png)
Looks good 👍

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/37196044-2f5f1abc-23b0-11e8-9e69-72bc6080c906.png)

Store with vertices array offset, NOT line num

**Comment by Jeremzzzz** [comment]
Thanks
